### ISSUE TITLE
Главный вопрос. Ты токен ввел на travis-ci.*org*? :)

### ISSUE THREAD

**Issue by vaganov-spb** [vaganov-spb/2019-2-Track-Frontend-T-Vaganov#3]
Да,я уже пытался и Update token делать и Regenerate(с последующим изменением в travis)

Главный вопрос. Ты токен ввел на travis-ci.*org*? :)

_Originally posted by @chexex in https://github.com/vaganov-spb/2019-2-Track-Frontend-T-Vaganov/pull/2#issuecomment-536304387_

**Comment by chexex** [comment]
Дай пруф, что у тебя на travis-ci.org заведен токен (не на travis-ci.com) :)

**Comment by chexex** [comment]
https://travis-ci.org/vaganov-spb/2019-2-Track-Frontend-T-Vaganov

Тут сборка проходит

**Comment by chexex** [comment]
Покажи, какой трэвис у тебя подключен к гитхабу :)
